#!/bin/bash

rectangles=" "
SR=$(xrandr --query | grep ' connected' | grep -o '[0-9][0-9]*x[0-9][0-9]*[^ ]*')
for RES in $SR; do
        SRA=(${RES//[x+]/ })
        CX=$((${SRA[2]} + 25))
        CY=$((${SRA[1]} - 30))
        rectangles+="rectangle $CX,$CY $((CX+300)),$((CY-80)) "
done

maim | convert - -fill black -colorize 40% -blur 0x5 -draw "fill black fill-opacity 0.4 $rectangles" /tmp/screenshotblur.png

i3lock \
        -t -n -i "/tmp/screenshotblur.png" \
        --timepos="x-90:h-ch+30" \
        --datepos="tx+24:ty+25" \
        --clock --datestr "Type password to unlock..." \
        --insidecolor=00000000 --ringcolor=ffffffff --line-uses-inside \
        --keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000 \
        --insidevercolor=00000000 --insidewrongcolor=d23c3dff \
        --ringvercolor=ffffffff --ringwrongcolor=ffffffff --indpos="x+280:h-70" \
        --radius=20 --ring-width=4 --veriftext="" --wrongtext="" \
        --textcolor="ffffffff" --timecolor="ffffffff" --datecolor="ffffffff" \
        --force-clock
